apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: riser-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - "deployments/status"
  verbs:
  - get
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  - revisions
  - routes
  verbs:
  - get
  - list
  - watch

